references:
  ipdr-build-image: &ipdr-build-image
    circleci/classic:latest

version: 2
jobs:
  build:
    machine:
      image: *ipdr-build-image

    working_directory: /home/circleci/.go_workspace/src/github.com/ipdr/ipdr
    steps:
      - run:
          name: Install Golang
          command: |
            sudo apt-get update -y
            cd /tmp
            wget https://dl.google.com/go/go1.11.linux-amd64.tar.gz
            sudo tar -xvf go1.11.linux-amd64.tar.gz
            sudo rm -rf /usr/local/go
            sudo mv go /usr/local
            export GOPATH=/home/circleci/.go_workspace
            export PATH=$PATH:$GOPATH/bin
            go version

      - run:
          name: Install Docker
          command: |
            set -x
            VER="18.09.3"
            curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            sudo mv /tmp/docker/* /usr/bin

      - run:
          name: Install IPFS
          command: |
            set -x
            wget https://dist.ipfs.io/go-ipfs/v0.4.19/go-ipfs_v0.4.19_linux-amd64.tar.gz -O /tmp/go-ipfs.tar.gz
            cd /tmp
            tar xvfz go-ipfs.tar.gz
            sudo cp go-ipfs/ipfs /home/circleci/bin/
            ipfs version

      - run:
          name: Configure IPFS
          command: |
            ipfs init
            ipfs config Addresses.API /ip4/0.0.0.0/tcp/5001
            ipfs config Addresses.Gateway /ip4/0.0.0.0/tcp/8080

      - run: echo '127.0.0.1 docker.localhost' | sudo tee -a /etc/hosts

      - checkout

      - run:
          name: Tests
          command: |
            ipfs daemon --offline & make test

workflows:
  version: 2
  all:
    jobs:
      - build
